[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    # Fluent Bit đọc trực tiếp log từ Docker Container của App
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               app.logs
    Refresh_Interval  5

[FILTER]
    # Bước này để bóc lớp vỏ JSON của Docker ra lấy nội dung thực tế (message)
    Name         parser
    Match        app.logs
    Key_Name     log
    Parser       json_python
    Reserve_Data True

[OUTPUT]
    # Đẩy log đã được bóc tách sang Loki
    Name          loki
    Match         app.logs
    Host          loki
    Port          3100
    # Gắn Label để trên Grafana có thể lọc theo User hoặc Hành động
    Labels        job=healthcare-api, env=dev, action=$action, user=$user_id
    Auto_Labels   on