[PARSER]
    Name        json
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S
    # Giữ nguyên kiểu dữ liệu (số ra số, chữ ra chữ)
    Types       code:integer
    # Cho phép giải mã các trường JSON lồng nhau bên trong (nếu có)
    Decode_Field_As esc:json log
[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf
[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       json
    # Giữ lại các trường khác nếu parse lỗi (tránh mất log)
    Preserve_Key On
    Reserve_Data On